# BERTopic Modeling

### Loading necessary libraries

In [27]:
import pandas as pd
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from bertopic.representation import MaximalMarginalRelevance

## EDA & Preprocessing

### Loading and Previewing Dataset

In [28]:
# Define the path to the CSV file
file_path = "../data/spotify_reviews_clean&PP_NoEmoji_V2.csv"

# Load the dataset from the specified CSV file using pandas
data = pd.read_csv(file_path)

# Display the first five rows of the dataframe to check the data's initial structure
data.head()

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion,thumbsUpBins,review_length,review_word_count,language,emojis
0,deaff34b-8743-47ee-b464-1d797e3ac0b1,Katie Watson,spotify extremely degraded time let non premiu...,1,3349,8.9.34.590,2024-04-30 14:12:05,8.9.34.590,1001-10000,473,86,en,[]
1,94918b0a-9544-4d68-a903-4b65777560e0,Gurnam Kaur Bajwa,frustrate playback issue spotify use music app...,1,2585,8.9.32.624,2024-04-21 16:20:35,8.9.32.624,1001-10000,424,73,en,[]
2,e709d597-ae44-49c1-aef3-f9655b25ee69,Bhavithra Srinivasan,spotify year song need become worse day day wi...,2,268,8.9.34.590,2024-04-28 17:22:27,8.9.34.590,101-1000,483,89,en,[]
3,7004d18f-feb7-4a89-a1dd-051cfe907ad9,Anushma Roy,new update absolutely disgust feature availabl...,1,298,8.9.32.624,2024-04-27 17:33:08,8.9.32.624,101-1000,345,62,en,[]
4,dbed7578-afc9-4a58-b426-ce9adef1cf61,Yohan Billimoria,premium user app become utter garbage music pl...,1,1303,8.9.34.590,2024-04-27 05:14:29,8.9.34.590,1001-10000,500,93,en,[]

### Data Preprocessing

In [29]:
# Extracting reviews into a list from the 'content' column
reviews = data['content'].tolist()

## Initializing Topic Modeling

In [30]:
# Creating a topic model with detailed settings

# Load the all-MiniLM-L6-v2 model from sentence-transformers
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
# Load the MaximalMarginalelevance model to increase granularity
representation_model = MaximalMarginalRelevance(diversity=0.7)

# Initialize BERTopic
topic_model = BERTopic(language="english", calculate_probabilities=True,
                       verbose=True, representation_model=representation_model,
                       top_n_words=10, embedding_model=embedding_model, min_topic_size=10)

## Topic Modeling on all Reviews

### Fitting the Topic Model to Reviews

In [31]:
# Generating topics and their probabilities
topics, probabilities = topic_model.fit_transform(reviews)

2024-05-30 17:23:36,223 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 2257/2257 [01:48<00:00, 20.77it/s]
2024-05-30 17:25:25,951 - BERTopic - Embedding - Completed ✓
2024-05-30 17:25:25,954 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-05-30 17:25:52,267 - BERTopic - Dimensionality - Completed ✓
2024-05-30 17:25:52,271 - BERTopic - Cluster - Start clustering the reduced embeddings
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
2024-05-30 17:27:56,134 - BERTopic - Cluster - Completed ✓
2024-05-30 17:27:56,186 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-05-30 17:28:13,391 - BERTopic - Representation - Completed ✓

In [32]:
# Getting information about the topics found in the dataset
topic_info = topic_model.get_topic_info()

### Saving the Fitted Model

In [33]:
topic_model.save("spotify_reviews_topic_model")

2024-05-30 17:28:14,294 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

### Visualizations of Topics

In [34]:
# Printing number of Topics
freq = topic_model.get_topic_info()
print("Number of topics: {}".format( len(freq)))
freq.head()

Number of topics: 225

,Topic,Count,Name,Representation,Representative_Docs
0,-1,44078,-1_spotify_premium_listen_play,"[spotify, premium, listen, play, add, love, sk...",[one thing dont like spotify buy premium order...
1,0,6666,0_offline_crash_pause_reinstall,"[offline, crash, pause, reinstall, app, wifi, ...",[know happen keep put offline mode turn say in...
2,1,3989,1_podcast_jre_listen_rogan,"[podcast, jre, listen, rogan, video, app, rand...",[worst music podcast app music discovery like ...
3,2,1136,2_premium_skip_money_random,"[premium, skip, money, random, playlist, limit...",[really force buy premium need premium even pl...
4,3,1061,3_bluetooth_start_via_autoplay,"[bluetooth, start, via, autoplay, disconnect, ...",[would better set stop spotify automatically s...

In [35]:
print(topic_model.get_topic_info())

     Topic  Count                                              Name  \
0       -1  44078                    -1_spotify_premium_listen_play
1        0   6666                   0_offline_crash_pause_reinstall
2        1   3989                        1_podcast_jre_listen_rogan
3        2   1136                       2_premium_skip_money_random
4        3   1061                    3_bluetooth_start_via_autoplay
..     ...    ...                                               ...
220    219     10              219_eaven_2mins_incentivize_restrict
221    220     10  220_deadspot_incompatibility_highschool_canceled
222    221     10               221_report_noncreators_usuallt_farm
223    222     10            222_depression_calm_regulate_shittiest
224    223     10                223_autoplay_queue_whenever_hiding

                                        Representation  \
0    [spotify, premium, listen, play, add, love, sk...
1    [offline, crash, pause, reinstall, app, wifi, ...
2    [podcast, jre, listen, rogan, video, app, rand...
3    [premium, skip, money, random, playlist, limit...
4    [bluetooth, start, via, autoplay, disconnect, ...
..                                                 ...
220  [eaven, 2mins, incentivize, restrict, measure,...
221  [deadspot, incompatibility, highschool, cancel...
222  [report, noncreators, usuallt, farm, intolerab...
223  [depression, calm, regulate, shittiest, compan...
224  [autoplay, queue, whenever, hiding, suggest, a...

                                   Representative_Docs
0    [one thing dont like spotify buy premium order...
1    [know happen keep put offline mode turn say in...
2    [worst music podcast app music discovery like ...
3    [really force buy premium need premium even pl...
4    [would better set stop spotify automatically s...
..                                                 ...
220  [omg see control app need premium even listen ...
221  [spotify since google play music shut love shu...
222  [usuallt really enjoy app however last week st...
223  [app good really amazing satisfy stress proble...
224  [autoplay turn longer delete suggest track que...

[225 rows x 5 columns]

In [36]:
# !pip3 install --upgrade nbformat

In [37]:
# Intertopic Distance Map
topic_model.visualize_topics()

In [38]:
# Barchart visualisation to show top 10 topics to understand which words contribute to out topics
topic_model.visualize_barchart(width = 200, height = 330, top_n_topics = 10, n_words = 10)

In [39]:
# Hierarchical visualization to show the relationship between topics
topic_model.visualize_hierarchy()

In [40]:
# Heatmap visualization to show similarities between topics
topic_model.visualize_heatmap(n_clusters=20)

### Topics Over Time

In [41]:
# Ensure timestamps are datetime objects
data['at'] = pd.to_datetime(data['at'])
timestamps = data['at'].tolist()

# Set the number of bins for temporal analysis
nr_bins = 10  # Adjust this based date range and desired granularity

# Generate the topics over time data using the parameters
topics_over_time = topic_model.topics_over_time(docs=reviews, topics=topics, timestamps=timestamps, nr_bins=nr_bins)

# Visualize the topics over time
topic_model.visualize_topics_over_time(topics_over_time, top_n_topics= 10)

10it [01:46, 10.63s/it]

## Topic Modeling 01/11/2023 - 01/02/2024

### Filtering reviews to specified date range

In [49]:
# Ensure timestamps are datetime objects for the entire dataset
data['at'] = pd.to_datetime(data['at'])

# Filtering reviews from November 2023 to January 2024
nov_jan_reviews = data[(data['at'] >= '2023-11-01') & (data['at'] < '2024-02-01')]

# Displaying the first few rows of the filtered reviews
nov_jan_reviews.head()

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion,thumbsUpBins,review_length,review_word_count,language,emojis
2845,c113a900-d130-4c13-8cd1-4ef855e3c2c3,c v,pro spotify allows create playlist follow arti...,3,12,8.8.96.364,2024-01-16 01:42:36,8.8.96.364,11-100,500,91,en,[]
4354,4369d834-b8a8-4e91-95f0-2610f0b82516,Alisha Anwar,good quality great make playlist find song how...,3,587,8.8.96.364,2024-01-03 11:51:36,8.8.96.364,101-1000,399,72,en,[]
4357,468d5753-a64b-4285-99b5-c1b8a1a2badb,Jon Nehring,overall lot option select quality good app iss...,4,268,8.8.96.364,2023-12-22 19:17:01,8.8.96.364,101-1000,466,83,en,[]
4358,e12b14fc-7a21-4004-add3-9cd7b08c77a5,Elianah S.,even enjoy time spotify especially bluetooth h...,2,958,8.9.4.304,2024-01-14 00:13:48,8.9.4.304,101-1000,483,81,en,[]
4359,42f23747-d626-4a2c-a8a9-80902c3f7995,Carina Becker,love app especially basically listen music who...,3,212,8.9.6.458,2024-01-25 07:45:23,8.9.6.458,101-1000,377,70,en,[]

### Fitting Topic Model to Filtered Date

In [50]:
# Fitting the topic model to the filtered review content
filtered_topics, filtered_probs = topic_model.fit_transform(nov_jan_reviews['content'])

# Getting topic information for the newly filtered content
filtered_topic_info = topic_model.get_topic_info()

2024-05-30 17:49:06,445 - BERTopic - Embedding - Transforming documents to embeddings.

Batches: 100%|██████████| 412/412 [00:16<00:00, 24.45it/s]
2024-05-30 17:49:23,496 - BERTopic - Embedding - Completed ✓
2024-05-30 17:49:23,496 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-05-30 17:49:28,220 - BERTopic - Dimensionality - Completed ✓
2024-05-30 17:49:28,223 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-05-30 17:49:30,513 - BERTopic - Cluster - Completed ✓
2024-05-30 17:49:30,519 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-05-30 17:49:37,292 - BERTopic - Representation - Completed ✓

In [53]:
freq = topic_model.get_topic_info()
print("Number of topics: {}".format( len(freq)))
freq.head()

Number of topics: 88

,Topic,Count,Name,Representation,Representative_Docs
0,-1,7166,-1_app_play_spotify_premium,"[app, play, spotify, premium, shuffle, skip, a...",[like app like playlist make try listen spotif...
1,0,899,0_podcast_pay_app_scroll,"[podcast, pay, app, scroll, start, rogan, issu...",[idk happen last update add want listen next q...
2,1,402,1_spotify_enjoy_find_stream,"[spotify, enjoy, find, stream, year, listen, g...",[love everything app music easy use song song ...
3,2,286,2_worst_premium_music_listen,"[worst, premium, music, listen, everything, sk...",[one worst music app ever download let play ev...
4,3,254,3_heart_button_add_liked,"[heart, button, add, liked, playlist, bring, s...",[new button feature make app confuse many step...

### Visualizing Filtered Topics

In [54]:
# Intertopic Distance Map
topic_model.visualize_topics()

In [55]:
# Barchart visualisation to show top 10 topics to understand which words contribute to out topics
topic_model.visualize_barchart(width=300, height=330, top_n_topics=8, n_words = 10)

In [56]:
# Hierarchical visualization to show the relationship between topics
topic_model.visualize_hierarchy()

In [57]:
# Heatmap visualization to show similarities between topics
topic_model.visualize_heatmap(n_clusters=20)

### Generating Topics Over Time to Identify Relevant Topics

In [58]:
# Extract timestamps for the filtered reviews for temporal analysis
timestamps = nov_jan_reviews['at'].tolist()

# Check the lengths of each component
print("Length of nov_jan_reviews['content']:", len(nov_jan_reviews['content']))
print("Length of filtered_topics:", len(filtered_topics))
print("Length of timestamps:", len(timestamps))

# If lengths are the same, proceed with topic modeling over time
if len(nov_jan_reviews['content']) == len(filtered_topics) == len(timestamps):
    # Set the number of bins for temporal analysis
    nr_bins = 10  # Adjust this based on your filtered data's date range and granularity

    # Generate the topics over time data using the corrected parameters
    topics_over_time = topic_model.topics_over_time(docs=nov_jan_reviews['content'], topics=filtered_topics, timestamps=timestamps, nr_bins=nr_bins)

Length of nov_jan_reviews['content']: 13182
Length of filtered_topics: 13182
Length of timestamps: 13182

10it [00:46,  4.70s/it]

In [59]:
 # Visualize the topics over time
topic_model.visualize_topics_over_time(topics_over_time, top_n_topics=8)